export enum QRCodesErrors {
  'QRCODE_ALREADY_SCANNED' = 'QRCODE_ALREADY_SCANNED',
  'QRCODE_NOT_FOUND' = 'QRCODE_NOT_FOUND',
}

export enum SchedulesError {
  'SCHDEULE_NOT_FOUND' = 'SCHDEULE_NOT_FOUND',
  'SCHDEULE_HAS_PASSED' = 'SCHDEULE_HAS_PASSED',
  'SCHDEULE_ALREADY_LOGGED' = 'SCHDEULE_ALREADY_LOGGED',
  'SCHDEULE_HAS_NOT_OPENED' = 'SCHDEULE_HAS_NOT_OPENED',
}

export enum AuthError {
  'USER_ALREADY_REGISTERED' = 'USER_ALREADY_REGISTERED'
}